version: '3.1'

services:
  app:
    build: ./app
    container_name: app
    ports:
      - '8000:8000'
    volumes:
      - ./app:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    # stdin_open: true
    # tty: true
