# Generated by Django 2.0 on 2018-01-12 19:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='Asset Name', max_length=200, verbose_name='Name')),
                ('address', models.CharField(help_text='Asset Address', max_length=300, verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ('-created_on',),
            },
        ),
    ]
